Again, fix a nil error when the configurations table is empty
 Here is what I ended up with:

 ```
 NoMethodError: undefined method `>' for nil:NilClass
 /hack/maycamp_arena/releases/20150523182751/app/services/sync_tests.rb:9:in
 `call'
 /hack/maycamp_arena/releases/20150523182751/lib/grader.rb:3:in
 `initialize'
 /hack/maycamp_arena/releases/20150523182751/lib/tasks/grader.rake:6:in
 `new'
 /hack/maycamp_arena/releases/20150523182751/lib/tasks/grader.rake:6:in
 `block (2 levels) in <top (required)>''
 ```